// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import BatchControlController from "./batch_control_controller"
application.register("batch-control", BatchControlController)

import BlindControlController from "./blind_control_controller"
application.register("blind-control", BlindControlController)

import ChartController from "./chart_controller"
application.register("chart", ChartController)

import ColorPickerController from "./color_picker_controller"
application.register("color-picker", ColorPickerController)

import DebugCableController from "./debug_cable_controller"
application.register("debug-cable", DebugCableController)

import EventsController from "./events_controller"
application.register("events", EventsController)

import FanControlController from "./fan_control_controller"
application.register("fan-control", FanControlController)

import GarageDoorControlController from "./garage_door_control_controller"
application.register("garage-door-control", GarageDoorControlController)

import FavoritesController from "./favorites_controller"
application.register("favorites", FavoritesController)

import FloorplanViewerController from "./floorplan_viewer_controller"
application.register("floorplan-viewer", FloorplanViewerController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import LightControlController from "./light_control_controller"
application.register("light-control", LightControlController)

import LockControlController from "./lock_control_controller"
application.register("lock-control", LockControlController)

import MultiSelectController from "./multi_select_controller"
application.register("multi-select", MultiSelectController)

import RecentEventsController from "./recent_events_controller"
application.register("recent-events", RecentEventsController)

import RoomActivityController from "./room_activity_controller"
application.register("room-activity", RoomActivityController)

import SceneController from "./scene_controller"
application.register("scene", SceneController)

import SidebarController from "./sidebar_controller"
application.register("sidebar", SidebarController)

import SwitchControlController from "./switch_control_controller"
application.register("switch-control", SwitchControlController)

import ThermostatControlController from "./thermostat_control_controller"
application.register("thermostat-control", ThermostatControlController)

import ToastController from "./toast_controller"
application.register("toast", ToastController)
