source 'https://rubygems.org'

gem 'sinatra'
gem 'puma'
gem 'faraday'
gem 'faraday-retry'
gem 'json'
gem 'dotenv'

group :test do
  gem 'rspec'
  gem 'rack-test'
  gem 'webmock'
  gem 'vcr'
end

gem "rackup", "~> 2.3"
