require "active_support/core_ext/integer/time"

Rails.application.configure do
  # Settings specified here will take precedence over those in config/application.rb.

  config.hosts << "api.higroundsolutions.com"
  config.web_console.permissions = [ "192.168.0.0/16" ]
  # Make code changes take effect immediately without server restart.
  config.enable_reloading = true

  # Do not eager load code on boot.
  config.eager_load = false

  # Show full error reports.
  config.consider_all_requests_local = true

  # Enable server timing.
  config.server_timing = true

  # Enable/disable Action Controller caching. By default Action Controller caching is disabled.
  # Run rails dev:cache to toggle Action Controller caching.
  if Rails.root.join("tmp/caching-dev.txt").exist?
    config.action_controller.perform_caching = true
    config.action_controller.enable_fragment_cache_logging = true
    config.public_file_server.headers = { "cache-control" => "public, max-age=#{2.days.to_i}" }
  else
    config.action_controller.perform_caching = false
  end

  # Change to :null_store to avoid any caching.
  config.cache_store = :memory_store

  # Store uploaded files on the local file system (see config/storage.yml for options).
  config.active_storage.service = :local

  # Don't care if the mailer can't send.
  config.action_mailer.raise_delivery_errors = false

  # Make template changes take effect immediately.
  config.action_mailer.perform_caching = false

  # Set localhost to be used by links generated in mailer templates.
  config.action_mailer.default_url_options = { host: "localhost", port: 3016 }

  # Print deprecation notices to the Rails logger.
  config.active_support.deprecation = :log

  # Raise an error on page load if there are pending migrations.
  config.active_record.migration_error = :page_load

  # Highlight code that triggered database queries in logs.
  config.active_record.verbose_query_logs = true

  # Append comments with runtime information tags to SQL queries in logs.
  config.active_record.query_log_tags_enabled = true

  # Highlight code that enqueued background job in logs.
  config.active_job.verbose_enqueue_logs = true

  # Default to `:async` so the app works out-of-the-box in development without
  # having to run a separate worker process.
  #
  # If you want production-like behavior, start the worker (see `Procfile.dev`)
  # and opt in via `USE_SOLID_QUEUE=true` (or run Solid Queue in Puma via
  # `SOLID_QUEUE_IN_PUMA=true`).
  config.active_job.queue_adapter = if ENV["USE_SOLID_QUEUE"] == "true" || ENV["SOLID_QUEUE_IN_PUMA"] == "true"
    :solid_queue
  else
    :async
  end

  # Raises error for missing translations.
  # config.i18n.raise_on_missing_translations = true

  # Annotate rendered view with file names.
  config.action_view.annotate_rendered_view_with_filenames = false

  # Uncomment if you wish to allow Action Cable access from any origin.
  # config.action_cable.disable_request_forgery_protection = true

  # If the app is accessed through a different port (e.g., via a proxy on :80)
  # but Rails is running on :3016, set `ACTION_CABLE_URL` so the browser connects
  # to the correct websocket endpoint.
  # Example: ACTION_CABLE_URL=ws://192.168.4.253:3016/cable
  config.action_cable.url = ENV["ACTION_CABLE_URL"] if ENV["ACTION_CABLE_URL"].present?

  # Allow ActionCable from any dev host/IP (useful when hitting the app via LAN IP).
  # Tighten this later if needed.
  config.action_cable.allowed_request_origins = [
    %r{\Ahttp://},
    %r{\Ahttps://}
  ]

  # Propshaft note:
  # If `public/assets/.manifest.json` exists (e.g., from a prior `assets:precompile`),
  # Propshaft will switch to a static (manifest-only) resolver, which breaks importmap
  # in development because pinned JS assets won’t resolve.
  # Force a dev-only manifest path under `tmp/` so we use the dynamic resolver.
  config.assets.manifest_path = Rails.root.join("tmp", "propshaft-manifest.dev.json")

  # Raise error when a before_action's only/except options reference missing actions.
  config.action_controller.raise_on_missing_callback_actions = true

  # Apply autocorrection by RuboCop to files generated by `bin/rails generate`.
  # config.generators.apply_rubocop_autocorrect_after_generate!

  if defined?(Bullet)
    Bullet.enable = true
    Bullet.alert = true
    Bullet.bullet_logger = true
    Bullet.rails_logger = true
  end
end
